Gl 8 ex 2
Nixon-orel/Main pull request #2
Opened 2022-04-22 06:11 UTC by Nixon-orel

2022-04-22 07:43 UTC, msk-yv requested changes

2022-04-22 07:43 UTC, msk-yv commented on gl_5_ex_2.rb
> +def dist_between_points(xa,ya,xb,yb)
всё ещё не метод класса, и всё ещё принимает координаты, вместо объектов

2022-04-22 07:43 UTC, msk-yv commented on gl_6_ex_3.rb
> +def factorial(number)
прям точно не нужна рекурсия?

2022-04-22 07:43 UTC, msk-yv commented on gl_6_ex_4.rb
> +array_num = user_input.collect {|x| x.to_i}
по "код_стайлу" придирочка -` .collect { |x| some_math } `

2022-04-22 07:43 UTC, msk-yv commented on gl_6_ex_5.rb
> +if user_month = month_today && user_day <= day_today
вот тут идёт не сравнение, а присвоение, а оно в свою очередь всегда тру:)

2022-04-22 07:43 UTC, msk-yv commented on gl_6_ex_6_1.rb
> +        time_now = Time.now
эта переменная лишняя - можно сразу получить из Time.now.hour

2022-04-22 07:43 UTC, msk-yv commented on gl_6_ex_6_1.rb
> +    if hour_now < 6
сейчас тут 5 сравнений можно сделать 3

2022-04-22 07:43 UTC, msk-yv commented on gl_8_ex_2.rb
> +when 1
самое место для использования Hash :) Case странно применять здесь, но пусть:)

2022-04-24 08:03 UTC, closed without merging

2022-04-24 08:04 UTC, Nixon-orel commented
Неправильно изначально задал сравнение веток, сливать в майн не буду.