gl_15_ex_2_3
Nixon-orel/Main pull request #36
Opened 2022-05-22 10:08 UTC by Nixon-orel

2022-05-27 08:21 UTC, msk-yv requested changes

2022-05-27 08:21 UTC, msk-yv commented on gl_15_ex_2_3.rb
> +3.times do
посмотри как работает ```[].map.with_index { }```
будет однострочник если ещё ```[[1,2]].to_h``` посмотришь

2022-05-27 08:21 UTC, msk-yv commented on gl_15_ex_2_3.rb
> +puts array.map {|i| i + ": \'#{i.chars[0].capitalize + i.chars[-2] + i.chars[-1]}" + " (#{array.index(i)+1})\'"}
тут наверное всё-таки хэш должен в конце получиться? :)

2022-05-27 10:15 UTC, Nixon-orel commented on gl_15_ex_2_3.rb
> +puts array.map {|i| i + ": \'#{i.chars[0].capitalize + i.chars[-2] + i.chars[-1]}" + " (#{array.index(i)+1})\'"}
Нет, именно массив.

2022-05-29 07:59 UTC, msk-yv approved these changes

2022-05-29 10:36 UTC, merged