gl_15_ex_6
Nixon-orel/Main pull request #38
Opened 2022-05-22 11:03 UTC by Nixon-orel

2022-05-27 08:29 UTC, msk-yv requested changes

2022-05-27 08:29 UTC, msk-yv commented on gl_15_ex_6.rb
> +result = []
почитай про ```[]zip([])```

2022-05-27 10:14 UTC, Nixon-orel commented on gl_15_ex_6.rb
> +result = []
Да, так действительно проще.

2022-05-29 07:59 UTC, msk-yv approved these changes

2022-05-29 10:37 UTC, merged